### ISSUE TITLE
Fix: ownerOf() non-compliant to EIP-4973.

### ISSUE THREAD

**Issue by nftchance** [otterspace-xyz/otterspace-contracts#100]
This issue is opened to have the EIP misalignment (bug) rectified to prevent the compounding breaking of external services and loss of EIP support.

https://github.com/otterspace-xyz/otterspace-contracts/blob/1454d43aa52cf034d714673bfd970681de12ca4a/src/Badges.sol#L192

Standards are helpful because they allow other builders and organizations a way to build on top of what Otterspace is. If the EIP released and so heavily marketed is not even followed, finding support in the market will be very difficult.

Further, this functionality is part of the 721 standards (https://eips.ethereum.org/EIPS/eip-721), of which 4937 is heavily inspired.

```
    /// @notice Find the owner of an NFT
    /// @dev NFTs assigned to zero address are considered invalid, and queries
    ///  about them do throw.
    /// @param _tokenId The identifier for an NFT
    /// @return The address of the owner of the NFT
    function ownerOf(uint256 _tokenId) external view returns (address);
```

Though, as noted in the EIP, `ownerOf` is expected and an excellent decision to have throw when the token does not exist or is not owned (ideally even when revoked)! 4973 itself does mention this.

```
  /// @notice Find the address bound to an ERC4973 account-bound token
  /// @dev ABTs assigned to zero address are considered invalid, and queries
  ///  about them do throw.
  /// @param tokenId The identifier for an ABT.
  /// @return The address of the owner bound to the ABT.
  function ownerOf(uint256 tokenId) external view returns (address);
``` 

[Tim](https://ethereum-magicians.org/u/timdaub/summary) noted as of 3 hours ago, [here](https://ethereum-magicians.org/t/eip-4973-account-bound-tokens/8825/157) it appears that EIP-4937 is considering to no longer be used so I presume changes may be made, however this bug was introduced ~30 days ago that breaks away from the existing EIP (although still in draft).

**Comment by grp06** [comment]
closed, refer to #101 ... not necessary
