### ISSUE TITLE
Replace Chainclaim with ERC4973Permit and `mintWithPermission`

### ISSUE THREAD

**Issue by TimDaub** [otterspace-xyz/otterspace-contracts#48]
see file here: https://github.com/rugpullindex/ERC4973/blob/master/src/ERC4973Permit.sol

**Comment by rahulrumalla** [comment]
After spiking this, replacing chain-claim with mintWithPermission from ERC4973Permit can essentially get rid of `BadgeVendorFactory.sol` and its tests altogether. 

I'd like to align on the scope of what entails within this per my findings
- Remove chain-claim and replace with ERC4973Permit
- Remove ownable, as it is not necessary at this point and unsure yet on here where its best needed
- Most existing tests will become redundant as a lot of the test coverage for the core logic is within the libs itself
- Badges, mainly implements ERC4973 and doesn't introduce additional logic
- BadgeVendor's `takeBadge` will call `mintWithPermission`

The goal here is to mainly have working end-to-end mint/claim with `mintWithPermission` from this repo. 

If you agree, let's edit the issue's scope with this.

**Comment by TimDaub** [comment]
> After spiking this, replacing chain-claim with mintWithPermission from ERC4973Permit can essentially get rid of `BadgeVendorFactory.sol` and its tests altogether.

I think we can also get rid of BadgeVendor.sol, can't we?

> * BadgeVendor's `takeBadge` will call `mintWithPermission`

Why? Wouldn't it be better if the user/frontend directly called `mintWithPermission`?

**Comment by rahulrumalla** [comment]
>Why? Wouldn't it be better if the user/frontend directly called mintWithPermission?
I want to add some authorization rules around this, calling it from Vendor gives me that flexibility. And even to emit a local even that I could filter. 

Although, one can call minWithPermission directly anyway. But at least we'll be able to distinguish mints. Wdyt?

**Comment by TimDaub** [comment]
fixed
