### ISSUE TITLE
Store Badge Specs onchain

### ISSUE THREAD

**Issue by rahulrumalla** [otterspace-xyz/otterspace-contracts#50]
A Badge Spec is basically the design of the badge itself, from which actual vouchers are issued and badges minted against. It can be thought of as a JSON representation of badge params, uploaded to IPFS i.e., a badge spec is essential an IPFS uri. 

Issuers or DAO agents must publish their badge specs on-chain within this contract. This is mainly to add additional authorization that any badges minted have a direct reference to what spec they derived from. 

I think it would entail implementing the following 3
```
function createBadgeSpec(string calldata tokenURI);
function ownerOfSpec(string calldata tokenURI) public view returns (address);
event BadgeSpecCreated(address owner, string tokenURI);
```

I'm unsure of the right technical design for this just yet. Feedback would be much appreciated.

**Comment by rahulrumalla** [comment]
@TimDaub can you help provide feedback on approach, please?

**Comment by TimDaub** [comment]
What is the underlying problem? Why do we need this?
