### ISSUE TITLE
ROMP Token

### ISSUE THREAD

**Issue by rahulrumalla** [otterspace-xyz/otterspace-contracts#51]
A group of otters are called a romp :) 

A DAO or a unit of a DAO that can be a sort of like an admin or issuing authority for membership badges, need to be somehow represented on-chain, so that additional authorization can be applied i.e., issuing badge vouchers is only possible when you're representing a DAO on otterspace, which can be established by owning an NFT ($ROMP token). Essentially, registering a DAO can mint a $ROMP token which is a standard ERC721. 

The tokenURI could conform to EIP-4824 outlined in https://daostar.one/EIP

**Comment by rahulrumalla** [comment]
@TimDaub need feedback here please

**Comment by TimDaub** [comment]
Can you please frame this ticket around the problem. If we didn't have ROMP what would happen?
